Netflix Data cleaning

Libraries that I work with:

In [9]:
import numpy as np
import pandas as pd
from datetime import datetime

In [10]:
pd.set_option('display.max_columns', None)

Opening file and check top rows of Dataframe

In [11]:
netflixDf=pd.read_csv(r'Dataset\netflix_titles.csv')
netflixDf.head(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...

check shape of Dataframe

In [12]:
netflixDf.shape

(8807, 12)

Checking the data type of each column and the non-null number of values in each column

In [13]:
netflixDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

Creating a list of dataframe column names and strip string values

In [17]:
 columns = list(netflixDf.columns)
string_columns = list(netflixDf.columns)
string_columns.remove('release_year')
for i in string_columns:
    netflixDf[i]=netflixDf[i].str.strip()

In [ ]:
checking duplicate rows

In [7]:
netflixDf.duplicated().sum()

0

Missing values distribution

In [8]:
print ("Missing values distribution:")
print (netflixDf.isnull().mean())

Missing values distribution:
show_id         0.000000
type            0.000000
title           0.000000
director        0.299080
cast            0.093675
country         0.094357
date_added      0.001135
release_year    0.000000
rating          0.000454
duration        0.000341
listed_in       0.000000
description     0.000000
dtype: float64

fill null cell with ''

In [20]:
columnsN= ['director','cast','country','rating','date_added','rating']
for column in columnsN:
    netflixDf[column] = netflixDf[column].fillna('')

In [8]:
netflixDf.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

Extract more information for comparison from the table by creating month and year columns

In [21]:
rows = []
for i in range(len(netflixDf)):
    if netflixDf['date_added'].iloc[i] == '':
        rows.append(i)
netflixDf.loc[rows,:]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,,Anthony Bourdain,United States,,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,,Igor Dmitriev,,,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [11]:
month_added = []
year_added = []
for i in range(len(netflixDf)):
    if i in rows:
        month_added.append(0)
        year_added.append(0)
    else:
        date = netflixDf['date_added'].iloc[i].split(' ')
        month_added.append(date[0])
        year_added.append(int(date[2]))
        
for i , month in enumerate(month_added):
    if month != 0:
        datetime_obj = datetime.strptime(month, '%B')
        month_number = datetime_obj.month
        month_added[i] = month_number

netflixDf.insert(7,'month_added',month_added, allow_duplicates=True)
netflixDf.insert(8,'year_added',year_added, allow_duplicates=True)
netflixDf.head(7)

,show_id,type,title,director,cast,country,date_added,month_added,year_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",9,2021,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",9,2021,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",9,2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",9,2021,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",9,2021,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",,"September 24, 2021",9,2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",,"September 24, 2021",9,2021,2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...

In [12]:
netflixDf['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

Extraction of two extraction of two data frames for better comparison

In [25]:
tv_show =[]
movie = []
for i in range(len(netflixDf)):
    if netflixDf['type'].iloc[i]== 'TV Show':
        tv_show.append(i)
    else:
        movie.append(i)
netflixDf_show = netflixDf.loc[tv_show,:]
netflixDf_Movie = netflixDf.loc[movie, :]

netflixDf_show= netflixDf_show.set_index([pd.Index(range(0,len(netflixDf_show)))])
netflixDf_Movie= netflixDf_Movie.set_index([pd.Index(range(0,len(netflixDf_Movie)))])   
netflixDf_Movie.head(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
2,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
3,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
4,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
5,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
6,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",,,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...

getDuration function to specify TV Show , Movies length

In [23]:
def getDuration(data):
    count = 0
    durations = []
    for value in data:
	# filling in missing values
        if type(value) is float:
            durations.append(0)
        else:
            values = value.split(" ")
            durations.append(int(values[0]))
    return durations

Add column seasons to the netflixDf_show dataframe

In [26]:
netflixDf_show.insert(11,'seasons',getDuration(netflixDf_show['duration']))
netflixDf_show= netflixDf_show.drop(['duration'], axis = 1)
netflixDf_show.head(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,seasons,description
0,s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries",2,"After crossing paths at a party, a Cape Town t..."
1,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",1,To protect his family from a powerful drug lor...
2,s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",2021,TV-MA,"Docuseries, Reality TV",1,"Feuds, flirtations and toilet talk go down amo..."
3,s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",2,In a city of coaching centers known to train I...
4,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",,"September 24, 2021",2021,TV-MA,"TV Dramas, TV Horror, TV Mysteries",1,The arrival of a charismatic young priest brin...
5,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,"British TV Shows, Reality TV",9,A talented batch of amateur bakers face off in...
6,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",,,,"September 24, 2021",2021,TV-MA,"Crime TV Shows, Docuseries, International TV S...",1,"Sicily boasts a bold ""Anti-Mafia"" coalition. B..."

In [ ]:
Add column lenght to the netflixDf_Movie dataframe

In [27]:
netflixDf_Movie.insert(11,'length',getDuration(netflixDf_Movie['duration']))
netflixDf_Movie= netflixDf_Movie.drop(['duration'], axis = 1)
netflixDf_Movie.head(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,listed_in,length,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,Documentaries,90,"As her father nears the end of his life, filmm..."
1,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",,"September 24, 2021",2021,PG,Children & Family Movies,91,Equestria's divided. But a bright-eyed hero be...
2,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,"Dramas, Independent Movies, International Movies",125,"On a photo shoot in Ghana, an American model s..."
3,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,"Comedies, Dramas",104,A woman adjusting to life after a loss contend...
4,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,"Dramas, International Movies",127,After most of her family is murdered in a terr...
5,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",,"September 22, 2021",2021,TV-PG,"Children & Family Movies, Comedies",91,When the clever but socially-awkward Tetê join...
6,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",,,"September 22, 2021",2020,TV-MA,"Documentaries, International Movies",67,Declassified documents reveal the post-WWII li...

In [16]:
netflixDf_Movie['rating'].unique()

array(['PG-13', 'PG', 'TV-MA', 'TV-PG', 'TV-14', 'TV-Y', 'R', 'TV-G',
       'TV-Y7', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', '',
       'TV-Y7-FV', 'UR'], dtype=object)

In [17]:
netflixDf_show['rating'].unique()

array(['TV-MA', 'TV-14', 'TV-Y7', 'TV-PG', 'TV-Y', 'TV-G', 'R', 'NR', '',
       'TV-Y7-FV'], dtype=object)

In [18]:
incorrect_rating = ['74 min', '84 min', '66 min']
for i in range(len(netflixDf_Movie)):
    if netflixDf_Movie['rating'].iloc[i] in incorrect_rating:
        print(netflixDf_Movie.iloc[i])
        print("")

show_id                                                     s5542
type                                                        Movie
title                                             Louis C.K. 2017
director                                               Louis C.K.
cast                                                   Louis C.K.
country                                             United States
date_added                                          April 4, 2017
month_added                                                     4
year_added                                                   2017
release_year                                                 2017
rating                                                     74 min
length                                                          0
listed_in                                                  Movies
description     Louis C.K. muses on religion, eternal love, gi...
Name: 3562, dtype: object

show_id                                                     s5795
type                                                        Movie
title                                       Louis C.K.: Hilarious
director                                               Louis C.K.
cast                                                   Louis C.K.
country                                             United States
date_added                                     September 16, 2016
month_added                                                     9
year_added                                                   2016
release_year                                                 2010
rating                                                     84 min
length                                                          0
listed_in                                                  Movies
description     Emmy-winning comedy writer Louis C.K. brings h...
Name: 3738, dtype: object

show_id                                                     s5814
type                                                        Movie
title                        Louis C.K.: Live at the Comedy Store
director                                               Louis C.K.
cast                                                   Louis C.K.
country                                             United States
date_added                                        August 15, 2016
month_added                                                     8
year_added                                                   2016
release_year                                                 2015
rating                                                     66 min
length                                                          0
listed_in                                                  Movies
description     The comic puts his trademark hilarious/thought...
Name: 3747, dtype: object

Correcting the values of the rating and length columns for rows 3562, 3738 and 3738

In [19]:
index = [3562,3738,3738]

for i in index:
    split_value = netflixDf_Movie['rating'].iloc[i].split(' ')
    lenght = split_value[0]
    netflixDf_Movie['length'].iloc[i]=lenght
    netflixDf_Movie['rating'].iloc[i]='NR'

for i in index:
    print(netflixDf_Movie.iloc[i])

show_id                                                     s5542
type                                                        Movie
title                                             Louis C.K. 2017
director                                               Louis C.K.
cast                                                   Louis C.K.
country                                             United States
date_added                                          April 4, 2017
month_added                                                     4
year_added                                                   2017
release_year                                                 2017
rating                                                         NR
length                                                         74
listed_in                                                  Movies
description     Louis C.K. muses on religion, eternal love, gi...
Name: 3562, dtype: object
show_id                                                     s5795
type                                                        Movie
title                                       Louis C.K.: Hilarious
director                                               Louis C.K.
cast                                                   Louis C.K.
country                                             United States
date_added                                     September 16, 2016
month_added                                                     9
year_added                                                   2016
release_year                                                 2010
rating                                                         NR
length                                                         84
listed_in                                                  Movies
description     Emmy-winning comedy writer Louis C.K. brings h...
Name: 3738, dtype: object
show_id                                                     s5814
type                                                        Movie
title                        Louis C.K.: Live at the Comedy Store
director                                               Louis C.K.
cast                                                   Louis C.K.
country                                             United States
date_added                                        August 15, 2016
month_added                                                     8
year_added                                                   2016
release_year                                                 2015
rating                                                         NR
length                                                         66
listed_in                                                  Movies
description     The comic puts his trademark hilarious/thought...
Name: 3747, dtype: object

C:\Users\mrdav\AppData\Local\Temp\ipykernel_6804\4029104849.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netflixDf_Movie['length'].iloc[i]=lenght
C:\Users\mrdav\AppData\Local\Temp\ipykernel_6804\4029104849.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netflixDf_Movie['rating'].iloc[i]='NR'

Conversion of UR or Unrated values to NR or Not rated

In [21]:
for i in range(len(netflixDf_Movie)):
    if netflixDf_Movie['rating'].iloc[i] =='UR':
          netflixDf_Movie['rating'].iloc[i] = 'NR'
            
            
netflixDf_Movie['rating'].unique()

C:\Users\mrdav\AppData\Local\Temp\ipykernel_6804\2384513526.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netflixDf_Movie['rating'].iloc[i] = 'NR'

array(['PG-13', 'PG', 'TV-MA', 'TV-PG', 'TV-14', 'TV-Y', 'R', 'TV-G',
       'TV-Y7', 'G', 'NC-17', 'NR', '', 'TV-Y7-FV'], dtype=object)

In [23]:
netflixDf_Movie['country'].unique()

array(['United States', '',
       'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',
       'Germany, Czech Republic', 'India', 'United States, India, France',
       'China, Canada, United States',
       'South Africa, United States, Japan', 'Japan', 'Nigeria',
       'Spain, United States', 'France', 'United Kingdom, United States',
       'United Kingdom, Australia, France',
       'United Kingdom, Australia, France, United States',
       'United States, Canada', 'Germany, United States',
       'South Africa, United States', 'United States, Mexico',
       'United States, Italy, France, Japan',
       'United States, Italy, Romania, United Kingdom',
       'Australia, United States', 'Argentina, Venezuela',
       'United States, United Kingdom, Canada', 'China, Hong Kong',
       'Canada', 'Hong Kong', 'United States, China, Hong Kong',
       'Italy, United States', 'United States, Germany',
       'United Kingdom, Canada, United States',
       'United States, United Kingdom', 'United Kingdom', 'India, Nepal',
       'New Zealand, Australia, France, United States',
       'Italy, Brazil, Greece', 'Colombia', 'United States, Japan',
       'Mexico', 'Belgium, United Kingdom',
       'Switzerland, United Kingdom, Australia', 'South Africa',
       'Canada, United States', 'Brazil', 'Argentina', 'Argentina, Spain',
       'United States, Nigeria', 'Bulgaria, United States',
       'Spain, United Kingdom, United States', 'United States, China',
       'United States, France',
       'Spain, France, United Kingdom, United States',
       ', France, Algeria', 'Poland',
       'France, Israel, Germany, United States, United Kingdom',
       'Australia', 'New Zealand', 'Saudi Arabia', 'Thailand',
       'Indonesia', 'Egypt, Denmark, Germany', 'Italy',
       'United States, Switzerland', 'Hong Kong, Canada, United States',
       'Kuwait, United States', 'France, Canada, United States, Spain',
       'France, Netherlands, Singapore', 'Egypt', 'Malaysia',
       'South Korea, Czech Republic', 'South Korea', 'Vietnam',
       'United Kingdom, Belgium',
       'United Kingdom, Australia, United States',
       'France, Japan, United States',
       'United Kingdom, Germany, Spain, United States',
       'United Kingdom, United States, France, Italy',
       'United States, Germany, Canada',
       'United States, France, Italy, United Kingdom',
       'United States, United Kingdom, Germany, Hungary',
       'United States, New Zealand', 'Lebanon', 'Romania',
       'Lebanon, Syria', 'Philippines', 'Germany', 'United States, India',
       'China, United States, Canada', 'Lebanon, United Arab Emirates',
       'Canada, United States, Denmark', 'United Arab Emirates',
       'Mexico, France, Colombia', 'Netherlands', 'Spain', 'Sweden',
       'Germany, United States, France', 'United States, Bulgaria',
       'United Kingdom, France, Germany, United States',
       'Syria, France, Lebanon, Qatar', 'Belgium, Netherlands',
       'Mauritius', 'Canada, South Africa', 'Austria', 'Mexico, Brazil',
       'France, United States', 'China', 'Turkey', 'Germany, France',
       'United Kingdom, France, Spain, United States',
       'United States, Australia',
       'United States, United Kingdom, France', 'United States, Russia',
       'United States, United Kingdom, New Zealand',
       'Canada, Nigeria, United States',
       'France, United States, United Kingdom, Canada',
       'India, United Kingdom', 'Canada, United States, Mexico',
       'United Kingdom, Germany, United States',
       'Czech Republic, United Kingdom, United States', 'China, Taiwan',
       'United States, China, United Kingdom', 'Cameroon',
       'Lebanon, Palestine, Denmark, Qatar', 'Japan, United States',
       'Egypt, Saudi Arabia',
       'United Kingdom, France, Poland, Germany, United States',
       'Ireland, Switzerland, United Kingdom, France, United States',
       'China, United Kingdom', 'United Kingdom, South Africa, France',
       'Ireland, United Kingdom, France, Germany',
       'Russia, United States', 'United Kingdom, United States, France',
       'Taiwan', 'United Kingdom,',
       'United States, India, United Kingdom', 'Kenya',
       'Spain, Argentina', 'India, United Kingdom, France, Qatar',
       'Belgium, France', 'Argentina, Chile', 'United States, Thailand',
       'Chile, Brazil', 'Canada, United States, United Kingdom',
       'Uruguay', 'United States, Cambodia, Romania', 'Bangladesh',
       'Spain, Belgium, United States',
       'United Kingdom, United States, Australia',
       'Portugal, United States', 'Portugal, Spain',
       'India, United States', 'United Kingdom, Ireland',
       'United Kingdom, Spain, United States', 'Hungary, United States',
       'United States, South Korea',
       'Canada, United States, Cayman Islands', 'India, France',
       'France, Canada', 'Canada, Hungary, United States', 'Norway',
       'United Kingdom, Germany, France, United States',
       'France, Algeria',
       'Philippines, Canada, United Kingdom, United States',
       'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong',
       'Singapore', 'France, Belgium', 'Iceland',
       'United States, France, Serbia', 'United States, Italy',
       'Hong Kong, United States',
       'United States, Malta, France, United Kingdom',
       'United States, China, Canada', 'Lebanon, Canada, France',
       'Spain, France, Canada', 'United States, China, Colombia',
       'Spain, Thailand, United States', 'Mexico, Spain',
       'Ireland, Luxembourg, Belgium', 'China, United States',
       'Canada, Belgium', 'Canada, United Kingdom',
       'Lebanon, United Arab Emirates, France, Switzerland, Germany',
       'France, Belgium, Italy',
       'Lebanon, United States, United Arab Emirates', 'Lebanon, France',
       'France, Lebanon', 'France, Lebanon, United Kingdom',
       'France, Norway, Lebanon, Belgium',
       'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands',
       'United States, United Kingdom, India', 'Indonesia, Netherlands',
       'Turkey, South Korea', 'Serbia, United States', 'Namibia',
       'United Kingdom, Kenya',
       'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany',
       'Thailand, United States',
       'United States, France, Canada, Belgium',
       'Germany, China, United Kingdom',
       'Hong Kong, Iceland, United States',
       'United States, Belgium, Canada, France', 'South Africa, Angola',
       'United States, Philippines',
       'United States, United Kingdom, Canada, China',
       'United States, Canada, United Kingdom', 'Turkey, United States',
       'Peru, Germany, Norway', 'Mozambique', 'Brazil, France',
       'China, Spain, South Korea, United States', 'Spain, Germany',
       'Hong Kong, China', 'France, Belgium, Luxembourg, Cambodia,',
       'Indonesia, United Kingdom',
       'Switzerland, France, Belgium, United States', 'Ghana',
       'Spain, France, Canada, United States', 'United Kingdom, Nigeria',
       'Chile', 'France, Egypt', 'Egypt, France',
       'France, Brazil, Spain, Belgium', 'Egypt, Algeria',
       'Canada, South Korea, United States', 'Nigeria, United Kingdom',
       'United Arab Emirates, Jordan, Lebanon, Saudi Arabia',
       'Saudi Arabia, United Arab Emirates', 'Zimbabwe',
       'United Kingdom, Germany, United Arab Emirates, New Zealand',
       'Romania, United States', 'Mexico, United States', 'Kuwait',
       'Canada, Nigeria',
       'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States',
       'India, United Kingdom, China, Canada, Japan, South Korea, United States',
       'Turkey, India', 'Italy, Turkey',
       'United Kingdom, United States, Japan',
       'France, Belgium, United States', 'Uruguay, Argentina',
       'United States, United Kingdom, Japan', 'United States, Argentina',
       'United Kingdom, Italy', 'Ireland, United Kingdom',
       'United Kingdom, France, Belgium, Canada, United States',
       'Netherlands, Germany, Denmark, United Kingdom', 'Hungary',
       'Pakistan, United States', 'Romania, France, Switzerland, Germany',
       'Romania, United Kingdom', 'France, Malta, United States',
       'United Kingdom, France, Belgium, Ireland, United States',
       'United States, Norway, Canada', 'Poland, United States',
       'Kenya, United States', 'Uruguay, Argentina, Germany, Spain',
       'United States, United Kingdom, France, Germany, Japan',
       'United States, France, Japan',
       'United Kingdom, France, United States',
       'Spain, France, United States',
       'Indonesia, South Korea, Singapore', 'South Korea, United States',
       'United States, Spain', 'Argentina, Uruguay, Serbia',
       'Israel, United States', 'France, Japan',
       'United Kingdom, United States, Germany, Denmark, Belgium, Japan',
       'India, Germany', 'India, United Kingdom, Canada, United States',
       'Philippines, United States', 'Romania, Bulgaria, Hungary',
       'Uruguay, Guatemala', 'France, Senegal, Belgium', 'Canada, Norway',
       'Finland, Germany, Belgium', 'United Kingdom, France',
       'United States, Chile', 'United Kingdom, Japan, United States',
       'Spain, United Kingdom', 'United States, South Korea, Japan',
       'United Kingdom, Hungary, Australia', 'Italy, Belgium',
       'United States, United Kingdom, Germany', 'Switzerland',
       'Singapore, Malaysia',
       'France, Belgium, Luxembourg, Romania, Canada, United States',
       'South Africa, Nigeria', 'Spain, France',
       'United Kingdom, Hong Kong', 'Pakistan', 'Brazil, United States',
       'Denmark, Brazil, France, Portugal, Sweden', 'India, Turkey',
       'Philippines, Singapore', 'Taiwan, China, France, United States',
       'Germany, Italy', 'Colombia, Peru, United Kingdom',
       'Thailand, China, United States', 'Argentina, United States',
       'Sweden, United States', 'Uruguay, Spain, Mexico',
       'France, Luxembourg, Canada', 'Denmark, Spain', 'Chile, Argentina',
       'United Kingdom, Belgium, Sweden', 'Denmark', 'Italy, France',
       'Canada, Germany', 'Pakistan, United Arab Emirates',
       'Ghana, United States', 'Mexico, Finland',
       'United Arab Emirates, United Kingdom, India',
       'Netherlands, Belgium', 'United States, Taiwan',
       'Austria, Iraq, United States', 'United Kingdom, Malawi',
       'Paraguay, Argentina', 'United Kingdom, Russia, United States',
       'India, Pakistan', 'Indonesia, Singapore', 'Spain, Belgium',
       'Iceland, Sweden, Belgium', 'Uruguay, Argentina, Spain',
       'Canada, Germany, France, United States', 'United Kingdom, Japan',
       'Norway, Denmark, Netherlands, Sweden',
       'Hong Kong, China, United States', 'Ireland, Canada',
       'Italy, Switzerland, France, Germany', 'Mexico, Netherlands',
       'France, Iran, United States', 'United Kingdom, India',
       'Russia, Poland, Serbia', 'Spain, Portugal', 'Peru',
       'Mexico, Argentina',
       'United Kingdom, Canada, United States, Cayman Islands',
       'Indonesia, United States',
       'United States, Israel, United Kingdom, Canada',
       'Norway, Iceland, United States',
       'United Kingdom, India, United States', 'India, Australia',
       'United States,', 'Belgium, United Kingdom, United States',
       'India, Germany, Austria', 'Spain, Mexico', 'China, Japan',
       'Argentina, France', 'China, United States, United Kingdom',
       'France, Luxembourg, United States',
       'China, United States, Australia', 'Colombia, Mexico',
       'United States, Canada, Ireland', 'Israel', 'Chile, Peru',
       'Argentina, Italy', 'Canada, Japan, United States',
       'United Kingdom, Canada, United States, Germany',
       'Italy, Switzerland, Albania, Poland', 'Cambodia',
       'Italy, United States, Argentina',
       'United States, Canada, Indonesia, United Kingdom, China, Singapore',
       'Spain, Colombia', 'Bulgaria',
       'Argentina, Brazil, France, Poland, Germany, Denmark',
       'United Kingdom, Spain, United States, Germany',
       'Philippines, Qatar', 'Netherlands, Belgium, Germany, Jordan',
       'United Arab Emirates, United States', 'United Kingdom, Germany',
       'United Kingdom, Canada', 'Georgia', 'Soviet Union, India',
       'Australia, United Arab Emirates', 'Czech Republic, United States',
       'South Korea, China, United States', 'India, Soviet Union',
       'India, Mexico', 'Georgia, Germany, France',
       'United Arab Emirates, Romania', 'Australia, Canada',
       'India, Malaysia', 'Germany, Jordan, Netherlands',
       'Turkey, France, Germany, Poland', 'Greece, United States',
       'Norway, Germany', 'France, Morocco', 'Cambodia, United States',
       'United States, Denmark',
       'United Kingdom, Italy, Israel, Peru, United States',
       'Argentina, Uruguay, Spain, France',
       'United Kingdom, France, United States, Belgium',
       'France, Canada, China, Cambodia',
       'United Kingdom, France, Belgium, United States', 'Ireland',
       'Chile, France', 'Netherlands, United States',
       'France, United Kingdom, India', 'Czech Republic, Slovakia',
       'Singapore, France', 'Spain, Switzerland',
       'United States, Australia, China',
       'South Africa, United States, Germany', 'Spain, Italy, Argentina',
       'Chile, Spain, Argentina, Germany', 'West Germany',
       'Austria, Czech Republic', 'Lebanon, Qatar',
       'United Kingdom, Jordan, Qatar, Iran',
       'France, South Korea, Japan', 'Israel, Germany, France',
       'United States, Hungary', 'France, Qatar',
       'United Kingdom, Germany, Canada', 'Ireland, South Africa',
       'Chile, United States, France', 'Denmark, United States',
       'Canada, United Kingdom, United States',
       'Belgium, France, Netherlands',
       'United Kingdom, Ukraine, United States',
       'United States, Bermuda, Ecuador',
       'United Kingdom, Egypt, United States',
       'United States, France, United Kingdom', 'Spain, Mexico, France',
       'United States, South Africa', 'Hong Kong, China, Singapore',
       'South Africa, China, United States', 'Denmark, France, Poland',
       'New Zealand, United Kingdom',
       'Netherlands, Denmark, South Africa', 'Iran, France',
       'United Kingdom, United States, France, Germany',
       'Australia, France', 'Ireland, United Kingdom, United States',
       'Spain, Italy', 'United Kingdom, France, Germany',
       'Canada, Luxembourg',
       'Brazil, Netherlands, United States, Colombia, Austria, Germany',
       'France, Canada, Belgium',
       'Bulgaria, United States, Spain, Canada', 'Sweden, Netherlands',
       'France, United States, Mexico',
       'Australia, United Kingdom, United Arab Emirates, Canada',
       'Singapore, United States',
       'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay',
       'India, Iran', 'France, Belgium, Spain',
       'Denmark, Sweden, Israel, United States', 'United States, Iceland',
       'United Kingdom, Russia', 'Netherlands, Denmark, France, Germany',
       'South Korea, Japan', 'United Kingdom, Pakistan',
       'France, New Zealand',
       'United Kingdom, Czech Republic, United States, Germany, Bahamas',
       'China, Germany, India, United States', 'Germany, Sri Lanka',
       'United States, Sweden', 'United States, India, Bangladesh',
       'United States, Canada, France', 'Brazil, France, Germany',
       'United States, United Kingdom, Australia',
       'Germany, United States, Hong Kong, Singapore',
       'France, Germany, Switzerland',
       'Germany, France, Luxembourg, United Kingdom, United States',
       'United Kingdom, Canada, Italy', 'Czech Republic, France',
       'Taiwan, Hong Kong, United States, China', 'Germany, Australia',
       'United Kingdom, Poland, United States', 'Denmark, Zimbabwe',
       'United Kingdom, South Africa',
       'Finland, Sweden, Norway, Latvia, Germany',
       'South Africa, United States, New Zealand, Canada',
       'United States, Italy, United Kingdom, Liechtenstein',
       'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom',
       'United States, Australia, Mexico',
       'United Kingdom, Czech Republic, Germany, United States',
       'France, China, Japan, United States', 'Germany, Belgium',
       'Pakistan, Norway, United States',
       'United States, Canada, Belgium, United Kingdom', 'Venezuela',
       'Canada, France, Italy, Morocco, United States',
       'Canada, Spain, France', 'United States, Indonesia',
       'Spain, France, Italy',
       'United Arab Emirates, United States, United Kingdom',
       'United Kingdom, Israel, Russia', 'United States, Brazil',
       'United States, France, Mexico', 'United States, Nicaragua',
       'France, United Kingdom, United States',
       'United Kingdom, United States, Spain, Germany, Greece, Canada',
       'Russia', 'United Kingdom, Denmark, Canada, Croatia',
       'United States, France, United Kingdom, Japan',
       'United States, United Kingdom, Denmark, Sweden',
       'United States, United Kingdom, Italy',
       'United States, France, Canada, Spain',
       'Russia, United States, China', 'United States, Canada, Germany',
       'Ireland, United States', 'United States, United Arab Emirates',
       'United States, Ireland',
       'Ireland, United Kingdom, Italy, United States', 'Poland,',
       'Slovenia, Croatia, Germany, Czech Republic, Qatar',
       'Canada, United Kingdom, Netherlands',
       'United States, Spain, Germany', 'India, Japan',
       'China, South Korea, United States',
       'United Kingdom, France, Belgium',
       'Canada, Ireland, United States',
       'United Kingdom, United States, Dominican Republic',
       'United States, Senegal', 'Germany, United Kingdom, United States',
       'South Africa, Germany, Netherlands, France',
       'Ireland, United States, France', 'Germany, United States, Canada',
       'United Kingdom, Germany, Canada, United States',
       'United States, France, Canada, Lebanon, Qatar',
       'Netherlands, Belgium, United Kingdom, United States',
       'France, Belgium, China, United States',
       'United States, Chile, Israel',
       'United Kingdom, Norway, Denmark, Germany, Sweden',
       'Norway, Denmark, Sweden', 'China, India, Nepal',
       'United Kingdom, South Korea', 'Denmark, China',
       'United States, Greece, Brazil',
       'United States, Australia, Samoa, United Kingdom',
       'Germany, United Kingdom', 'Argentina, Chile, Peru',
       'Poland, West Germany', 'Germany, United States, Sweden',
       'Canada, Spain', 'United States, Cambodia',
       'United States, Greece', 'Norway, United Kingdom, France, Ireland',
       'United Kingdom, Poland', 'Israel, Sweden, Germany, Netherlands',
       'Switzerland, France', 'Italy, India', 'United States, Botswana',
       'Chile, Argentina, France, Spain, United States',
       'United States, India, South Korea, China',
       'Denmark, Germany, Belgium, United Kingdom, France',
       'Denmark, Germany, Belgium, United Kingdom, France, Sweden',
       'France, Switzerland, Spain, United States, United Arab Emirates',
       'Brazil, India, China, United States',
       'Denmark, France, United States, Sweden', 'Australia, Iraq',
       'China, Morocco, Hong Kong', 'Canada, United States, Germany',
       'United Kingdom, Thailand', 'Venezuela, Colombia',
       'France, Germany, Czech Republic, Belgium',
       'Switzerland, Vatican City, Italy, Germany, France',
       'Portugal, France, Poland, United States', 'India, Switzerland',
       'Canada, India', 'United States, Morocco',
       'Singapore, Japan, France',
       'Canada, Mexico, Germany, South Africa',
       'United Kingdom, United States, Canada',
       'Germany, France, United States, Canada, United Kingdom',

Function to find unique values in a column

In [24]:
def uniqueItem(data):
    unique_value = set()
    for value in data:
        if type(value) is float:
            unique_value.add(None)
        else:
            value = value.split(', ')
            for i in range(len(value)):
                unique_value.add(value[i])
    return list(unique_value)

In [25]:
country = uniqueItem(netflixDf_Movie['country'])
country

['',
 'Turkey',
 'Namibia',
 'Denmark',
 'Morocco',
 'Slovakia',
 'Panama',
 'Cambodia,',
 'Vietnam',
 'Bulgaria',
 'Sweden',
 'New Zealand',
 'Czech Republic',
 'Mexico',
 'Italy',
 'South Africa',
 'Latvia',
 'Samoa',
 'Mozambique',
 'Bangladesh',
 'India',
 'Ukraine',
 'Japan',
 'Jamaica',
 'Albania',
 'Greece',
 'United States',
 'Germany',
 'United States,',
 'Poland,',
 'Pakistan',
 'Brazil',
 'Chile',
 'Peru',
 'Nigeria',
 'Austria',
 'Ireland',
 'Sri Lanka',
 'Ethiopia',
 'Colombia',
 'Saudi Arabia',
 'Zimbabwe',
 'Argentina',
 'Luxembourg',
 'Iraq',
 'Hungary',
 'Cameroon',
 'Vatican City',
 'Uganda',
 'Kazakhstan',
 'Montenegro',
 'Philippines',
 'Lithuania',
 'Indonesia',
 'Romania',
 'South Korea',
 'Liechtenstein',
 'Cayman Islands',
 'Bahamas',
 'Venezuela',
 'Thailand',
 'Senegal',
 'Dominican Republic',
 'Portugal',
 'Canada',
 'Norway',
 'Mongolia',
 'Taiwan',
 'United Kingdom,',
 'China',
 'Angola',
 'Hong Kong',
 'Mauritius',
 'Croatia',
 'Singapore',
 'Algeria',
 'West Germany',
 'Cambodia',
 'Malaysia',
 'Botswana',
 'Lebanon',
 'Serbia',
 'Uruguay',
 'Palestine',
 'Belgium',
 'Burkina Faso',
 'Iceland',
 'Slovenia',
 'Egypt',
 'Poland',
 'France',
 'Malta',
 'Netherlands',
 'Afghanistan',
 'Iran',
 'Syria',
 'Ghana',
 'Georgia',
 'Soviet Union',
 'Bermuda',
 'Nepal',
 'Israel',
 'Ecuador',
 'Switzerland',
 'Malawi',
 'Armenia',
 'Australia',
 'Sudan',
 'Spain',
 'Somalia',
 'Guatemala',
 'Jordan',
 'United Arab Emirates',
 'East Germany',
 'Paraguay',
 'Kenya',
 'United Kingdom',
 'Finland',
 'Nicaragua',
 'Qatar',
 'Russia',
 'Kuwait']

Movies produced by Iran or made with the participation of Iran

In [30]:
iranMovei_index=[]
for i in range (len (netflixDf_Movie)):
    if 'Iran' in netflixDf_Movie['country'].iloc[i]:
        iranMovei_index.append(i)
for i in iranMovei_index:
    print (netflixDf_Movie.iloc[i])
    print("")
print(iranMovei_index)

show_id                                                     s4419
type                                                        Movie
title                                  The Other Side of the Wind
director                                             Orson Welles
cast            John Huston, Oja Kodar, Peter Bogdanovich, Sus...
country                               France, Iran, United States
date_added                                       November 2, 2018
month_added                                                    11
year_added                                                   2018
release_year                                                 2018
rating                                                          R
length                                                        122
listed_in              Classic Movies, Dramas, Independent Movies
description     On the last day of his life, a legendary direc...
Name: 2802, dtype: object

show_id                                                     s5642
type                                                        Movie
title                                            Under the Shadow
director                                             Babak Anvari
cast            Narges Rashidi, Avin Manshadi, Bobby Naderi, R...
country                       United Kingdom, Jordan, Qatar, Iran
date_added                                        January 7, 2017
month_added                                                     1
year_added                                                   2017
release_year                                                 2016
rating                                                      PG-13
length                                                         84
listed_in          Horror Movies, International Movies, Thrillers
description     During the Iran-Iraq conflict, a Tehran woman ...
Name: 3639, dtype: object

show_id                                                     s6057
type                                                        Movie
title                                                A Separation
director                                           Asghar Farhadi
cast            Leila Hatami, Peyman Moaadi, Shahab Hosseini, ...
country                                              Iran, France
date_added                                         March 16, 2019
month_added                                                     3
year_added                                                   2019
release_year                                                 2011
rating                                                      PG-13
length                                                        123
listed_in                            Dramas, International Movies
description     Amid an impasse in his marriage, a father in T...
Name: 3945, dtype: object

show_id                                                     s6294
type                                                        Movie
title                                           Beyond the Clouds
director                                             Majid Majidi
cast            Ishaan Khattar, Malavika Mohanan, Goutam Ghose...
country                                               India, Iran
date_added                                        August 10, 2018
month_added                                                     8
year_added                                                   2018
release_year                                                 2018
rating                                                      TV-14
length                                                        120
listed_in        Dramas, Independent Movies, International Movies
description     A youthful drug dealer in Mumbai must change h...
Name: 4142, dtype: object

[2802, 3639, 3945, 4142]